name: Test and Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic github.com/kubeopsskills/cloud-secret-resolvers/internal/csr github.com/kubeopsskills/cloud-secret-resolvers/internal/utils
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)